// <auto-generated />
using System;
using AoE2DELobbyBrowser.WebApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AoE2DELobbyBrowser.WebApi.Database.Migrations
{
    [DbContext(typeof(MatchesDbContext))]
    partial class MatchesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("AoE2DELobbyBrowser.WebApi.Database.LobbiesTable", b =>
                {
                    b.Property<long>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IsObservable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MapType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("PlayerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Speed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("MatchId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("AoE2DELobbyBrowser.WebApi.Database.MatchesTable", b =>
                {
                    b.Property<long>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MatchId");

                    b.ToTable("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
