# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy to VPS

on:
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    env:
      projectPath: AoE2DELobbyBrowser.WebApi/AoE2DELobbyBrowser.WebApi.csproj
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Dump GitHub context
        run: |
          echo "$GITHUB_WORKSPACE"
          ls
          ls AoE2DELobbyBrowser.WebApi

      # build and publish    
      - name: Build and publish
        run: dotnet publish "AoE2DELobbyBrowser.WebApi/AoE2DELobbyBrowser.WebApi.csproj" -c Release -o publish -r linux-x64
    
      # Stop container
      - name: Stop container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: docker container stop aoe2deapi

      # Transfer Dockerfile
      - name: Copy Dockerfile
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          source: "Dockerfile"
          target: "/home/tmk/apps/aoe2deapi"

      # Transfer publish folder
      - name: Transfer publish folder
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          source: "publish/*"
          target: "/home/tmk/apps/aoe2deapi/publish"
          rm: true
      # Start container
      - name: Stop container
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: docker run -d -p 5100:8080 -e ASPNETCORE_URLS="http://*:8080" --name aoe2deapi aoe2delobbybrowser

